drop table IF EXISTS films CASCADE;
drop table IF EXISTS mpa CASCADE;
drop table IF EXISTS films_director CASCADE;
drop table IF EXISTS genre_types CASCADE;
drop table IF EXISTS genres CASCADE;

CREATE TABLE IF NOT EXISTS mpa (
    mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30)
);
CREATE TABLE IF NOT EXISTS films (
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_id INTEGER REFERENCES mpa (mpa_id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(200) NOT NULL,
    duration INTEGER NOT NULL,
    release_date DATE NOT NULL
);
CREATE TABLE IF NOT EXISTS films_director (
    director_id INTEGER REFERENCES directors (id) ON DELETE CASCADE,
    film_id INTEGER REFERENCES films (film_id) ON DELETE CASCADE,
    PRIMARY KEY (director_id, film_id)
);
CREATE TABLE IF NOT EXISTS genre_types (
    genre_types_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30)
);
CREATE TABLE IF NOT EXISTS genres (
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_types_id INTEGER REFERENCES genre_types (genre_types_id) ON DELETE CASCADE,
    film_id INTEGER REFERENCES films (film_id) ON DELETE CASCADE,
    UNIQUE (genre_types_id, film_id)
);